using System;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Timing;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Client.Graphics;

namespace Content.Client._Vortex.Communications.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CentcommConsoleMenu : FancyWindow
    {
        [Dependency] private readonly IGameTiming _timing = default!;

        public bool CountdownStarted { get; set; }
        public TimeSpan? CountdownEnd { get; set; }

        private TimeSpan? _errorRevertTime;
        private string? _originalLabelText;
        private NetEntity? _selectedStation;
        private string? _selectedThreatCode;
        private TimeSpan? _successMessageTimer;

        public event Action<float>? OnCallShuttle;
        public event Action? OnRecallShuttle;
        public event Action? OnViewManifest;
        public event Action? OnCreateFTLDisk;
        public event Action? OnToggleBSSCorridor;
        public event Action<NetEntity, string>? OnApplyThreatCode;

        public CentcommConsoleMenu()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            _originalLabelText = Loc.GetString("centcomm-console-arrival-time");

            // Set tab titles
            MainTabContainer.SetTabTitle(0, Loc.GetString("centcomm-console-communication-tab"));
            MainTabContainer.SetTabTitle(1, Loc.GetString("centcomm-console-evacuation-tab"));
            MainTabContainer.SetTabTitle(2, Loc.GetString("centcomm-console-bss-tab"));

            // Apply Centcomm console styling
            ApplyCentcommTabStyling();

            CallShuttleButton.OnPressed += _ => CallShuttlePressed();
            RecallShuttleButton.OnPressed += _ => RecallShuttlePressed();
            ViewManifestButton.OnPressed += _ => ViewManifestPressed();
            CreateFTLDiskButton.OnPressed += _ => CreateFTLDiskPressed();
            ToggleBSSCorridorButton.OnPressed += _ => ToggleBSSCorridorPressed();
            ApplyThreatCodeButton.OnPressed += _ => ApplyThreatCodePressed();

            // Handle dropdown selections
            StationSelector.OnItemSelected += OnStationSelected;
            ThreatCodeSelector.OnItemSelected += OnThreatCodeSelected;

            // Initialize BSS button with default status (will be updated when server responds)
            ToggleBSSCorridorButton.Text = Loc.GetString("centcomm-console-toggle-bss-corridor");
        }

        private void ApplyCentcommTabStyling()
        {
            // Centcomm console colors - authoritative and professional
            var centcommText = Color.White;                      // White text for contrast
            var centcommTextInactive = new Color(150, 160, 170, 255); // Muted text for inactive
            var centcommDark = new Color(20, 25, 35, 255);      // Very dark blue-gray
            var centcommBorder = new Color(50, 70, 90, 255);    // Medium blue-gray border
            var centcommBlue = new Color(0, 80, 120, 255);      // Deep blue for authority
            var centcommAccent = new Color(0, 150, 200, 255);   // Bright cyan accent

            // Set text colors
            MainTabContainer.TabFontColorOverride = centcommText;
            MainTabContainer.TabFontColorInactiveOverride = centcommTextInactive;

            // Custom panel background - dark and professional
            MainTabContainer.PanelStyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = centcommDark,
                BorderColor = centcommBorder,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 6,
                ContentMarginTopOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginBottomOverride = 6
            };
        }

        private void CallShuttlePressed()
        {
            if (!float.TryParse(ArrivalTimeInput.Text, out var arrivalTime) || arrivalTime < 5 || arrivalTime > 30)
            {
                ArrivalTimeInput.Text = "10"; // Reset to default
                ArrivalTimeLabel.Text = Loc.GetString("centcomm-console-arrival-time-invalid");
                ArrivalTimeLabel.FontColorOverride = Color.Red;
                _errorRevertTime = _timing.CurTime + TimeSpan.FromSeconds(4);
                _originalLabelText = Loc.GetString("centcomm-console-arrival-time");
                return;
            }

            OnCallShuttle?.Invoke(arrivalTime);
        }

        private void RecallShuttlePressed()
        {
            OnRecallShuttle?.Invoke();
        }

        private void ViewManifestPressed()
        {
            OnViewManifest?.Invoke();
        }

        private void CreateFTLDiskPressed()
        {
            OnCreateFTLDisk?.Invoke();
        }

        private void ToggleBSSCorridorPressed()
        {
            OnToggleBSSCorridor?.Invoke();
        }

        private void ApplyThreatCodePressed()
        {
            if (_selectedStation.HasValue && _selectedThreatCode != null)
            {
                // Disable button immediately to prevent spam clicking
                ApplyThreatCodeButton.Disabled = true;
                OnApplyThreatCode?.Invoke(_selectedStation.Value, _selectedThreatCode);
            }
        }

        public void PopulateStationSelector(Dictionary<NetEntity, string> stations)
        {
            StationSelector.Clear();
            var previouslySelectedStation = _selectedStation;

            foreach (var (stationId, name) in stations)
            {
                StationSelector.AddItem(name);
                StationSelector.SetItemMetadata(StationSelector.ItemCount - 1, stationId);
            }

            if (stations.Count > 0)
            {
                // Try to preserve previous selection, otherwise select first
                if (previouslySelectedStation.HasValue && stations.ContainsKey(previouslySelectedStation.Value))
                {
                    // Find the index of the previously selected station
                    var index = 0;
                    foreach (var (stationId, _) in stations)
                    {
                        if (stationId == previouslySelectedStation.Value)
                        {
                            StationSelector.Select(index);
                            break;
                        }
                        index++;
                    }
                }
                else
                {
                    // No previous selection or station no longer exists, select first
                    StationSelector.Select(0);
                    _selectedStation = stations.Keys.First();
                }
            }
        }

        public void PopulateThreatCodeSelector(Dictionary<string, string> threatCodes)
        {
            ThreatCodeSelector.Clear();
            var previouslySelectedCode = _selectedThreatCode;

            foreach (var (displayName, alertLevelId) in threatCodes)
            {
                ThreatCodeSelector.AddItem(displayName);
                ThreatCodeSelector.SetItemMetadata(ThreatCodeSelector.ItemCount - 1, displayName);
            }

            if (threatCodes.Count > 0)
            {
                // Try to preserve previous selection, otherwise select first
                if (!string.IsNullOrEmpty(previouslySelectedCode) && threatCodes.ContainsKey(previouslySelectedCode))
                {
                    // Find the index of the previously selected threat code
                    var index = 0;
                    foreach (var (displayName, _) in threatCodes)
                    {
                        if (displayName == previouslySelectedCode)
                        {
                            ThreatCodeSelector.Select(index);
                            break;
                        }
                        index++;
                    }
                }
                else
                {
                    // No previous selection or code no longer exists, select first
                    ThreatCodeSelector.Select(0);
                    _selectedThreatCode = threatCodes.Keys.First();
                }
            }
        }

        private void OnStationSelected(OptionButton.ItemSelectedEventArgs args)
        {
            var metadata = StationSelector.GetItemMetadata(args.Id);
            if (metadata is NetEntity station)
            {
                _selectedStation = station;
            }
            StationSelector.SelectId(args.Id);
        }

        private void OnThreatCodeSelected(OptionButton.ItemSelectedEventArgs args)
        {
            var metadata = ThreatCodeSelector.GetItemMetadata(args.Id);
            if (metadata is string threatCode)
            {
                _selectedThreatCode = threatCode;
            }
            ThreatCodeSelector.SelectId(args.Id);
        }

        public void OnThreatCodeApplied(bool success)
        {
            if (success)
            {
                ApplyThreatCodeButton.Text = "Успешно!";
                // Revert back to "Применить" after 3 seconds
                _successMessageTimer = _timing.CurTime + TimeSpan.FromSeconds(3);
            }
            else
            {
                ApplyThreatCodeButton.Text = "Применить";
            }
        }

        public void UpdateBSSButton(bool isOpen)
        {
            // Always show current status, with fallback if localization fails
            string statusText;
            if (isOpen)
            {
                statusText = Loc.TryGetString("centcomm-console-bss-corridor-open", out var openText)
                    ? openText
                    : "БСС Коридор: Открыт";
            }
            else
            {
                statusText = Loc.TryGetString("centcomm-console-bss-corridor-closed", out var closedText)
                    ? closedText
                    : "БСС Коридор: Закрыт";
            }

            ToggleBSSCorridorButton.Text = statusText;
        }

        public void UpdateCountdown()
        {
            // Handle error message revert
            if (_errorRevertTime.HasValue && _timing.CurTime >= _errorRevertTime.Value)
            {
                ArrivalTimeLabel.Text = _originalLabelText;
                ArrivalTimeLabel.FontColorOverride = null; // reset to default
                _errorRevertTime = null;
            }

            // Handle success message revert
            if (_successMessageTimer.HasValue && _timing.CurTime >= _successMessageTimer.Value)
            {
                ApplyThreatCodeButton.Text = "Применить";
                _successMessageTimer = null;
            }

            if (!CountdownStarted || CountdownEnd == null)
            {
                CountdownLabel.SetMessage("");
                return;
            }

            var timeLeft = CountdownEnd.Value - _timing.CurTime;
            if (timeLeft.TotalSeconds <= 0)
            {
                CountdownLabel.SetMessage(Loc.GetString("centcomm-console-shuttle-has-arrived"));
                return;
            }

            var timeString = timeLeft.ToString(@"mm\:ss");
            CountdownLabel.SetMessage(Loc.GetString("centcomm-console-shuttle-arrives-in", ("time", timeString)));
        }
    }
}