using System;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Timing;
using Robust.Shared.IoC;
using Robust.Shared.Maths;

namespace Content.Client._Vortex.Communications.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CentcommConsoleMenu : FancyWindow
    {
        [Dependency] private readonly IGameTiming _timing = default!;

        public bool CountdownStarted { get; set; }
        public TimeSpan? CountdownEnd { get; set; }

        private TimeSpan? _errorRevertTime;
        private string? _originalLabelText;

        public event Action<float>? OnCallShuttle;
        public event Action? OnRecallShuttle;
        public event Action? OnViewManifest;
        public event Action? OnCreateFTLDisk;
        public event Action? OnToggleBSSCorridor;

        public CentcommConsoleMenu()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            _originalLabelText = Loc.GetString("centcomm-console-arrival-time");

            CallShuttleButton.OnPressed += _ => CallShuttlePressed();
            RecallShuttleButton.OnPressed += _ => RecallShuttlePressed();
            ViewManifestButton.OnPressed += _ => ViewManifestPressed();
            CreateFTLDiskButton.OnPressed += _ => CreateFTLDiskPressed();
            ToggleBSSCorridorButton.OnPressed += _ => ToggleBSSCorridorPressed();
        }

        private void CallShuttlePressed()
        {
            if (!float.TryParse(ArrivalTimeInput.Text, out var arrivalTime) || arrivalTime < 5 || arrivalTime > 30)
            {
                ArrivalTimeInput.Text = "10"; // Reset to default
                ArrivalTimeLabel.Text = Loc.GetString("centcomm-console-arrival-time-invalid");
                ArrivalTimeLabel.FontColorOverride = Color.Red;
                _errorRevertTime = _timing.CurTime + TimeSpan.FromSeconds(4);
                _originalLabelText = Loc.GetString("centcomm-console-arrival-time");
                return;
            }

            OnCallShuttle?.Invoke(arrivalTime);
        }

        private void RecallShuttlePressed()
        {
            OnRecallShuttle?.Invoke();
        }

        private void ViewManifestPressed()
        {
            OnViewManifest?.Invoke();
        }

        private void CreateFTLDiskPressed()
        {
            OnCreateFTLDisk?.Invoke();
        }

        private void ToggleBSSCorridorPressed()
        {
            OnToggleBSSCorridor?.Invoke();
        }

        public void UpdateBSSButton(bool isOpen)
        {
            ToggleBSSCorridorButton.Text = Loc.GetString(isOpen ? "centcomm-console-bss-corridor-open" : "centcomm-console-bss-corridor-closed");
        }

        public void UpdateCountdown()
        {
            // Handle error message revert
            if (_errorRevertTime.HasValue && _timing.CurTime >= _errorRevertTime.Value)
            {
                ArrivalTimeLabel.Text = _originalLabelText;
                ArrivalTimeLabel.FontColorOverride = null; // reset to default
                _errorRevertTime = null;
            }

            if (!CountdownStarted || CountdownEnd == null)
            {
                CountdownLabel.SetMessage("");
                return;
            }

            var timeLeft = CountdownEnd.Value - _timing.CurTime;
            if (timeLeft.TotalSeconds <= 0)
            {
                CountdownLabel.SetMessage(Loc.GetString("centcomm-console-shuttle-has-arrived"));
                return;
            }

            var timeString = timeLeft.ToString(@"mm\:ss");
            CountdownLabel.SetMessage(Loc.GetString("centcomm-console-shuttle-arrives-in", ("time", timeString)));
        }
    }
}