using System.Linq;
using Content.Client.CrewManifest.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared.CrewManifest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;

namespace Content.Client._Vortex.Communications.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CentcommManifestWindow : DefaultWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        public event Action<NetEntity>? OnStationSelected;

        private NetEntity? _selectedStation;
        private Button? _selectedStationButton;

        public CentcommManifestWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            StationNameLabel.AddStyleClass("LabelBig");
        }

        public void Populate(Dictionary<NetEntity, string> stationNames, NetEntity? selectedStation, string selectedStationName, CrewManifestEntries? entries)
        {
            // Update station list
            StationList.RemoveAllChildren();
            foreach (var (stationId, name) in stationNames)
            {
                var button = new Button { Text = name };
                button.OnPressed += _ => SelectStation(button, stationId);
                if (stationId == selectedStation)
                {
                    button.ModulateSelfOverride = Color.FromHex("#274c8d");
                    _selectedStationButton = button;
                }
                StationList.AddChild(button);
            }

            // Update station name
            StationNameContainer.Visible = !string.IsNullOrEmpty(selectedStationName);
            StationNameLabel.Text = selectedStationName;

            // Update manifest
            ManifestListing.DisposeAllChildren();
            ManifestListing.RemoveAllChildren();

            if (entries != null)
            {
                ManifestListing.AddCrewManifestEntries(entries);
            }
            else
            {
                ManifestListing.AddChild(new Label { Text = Loc.GetString("crew-manifest-no-valid-station"), HorizontalExpand = true });
            }
        }

        private void SelectStation(Button button, NetEntity stationId)
        {
            // Reset previous button color
            if (_selectedStationButton != null)
            {
                _selectedStationButton.ModulateSelfOverride = null;
            }

            _selectedStationButton = button;
            _selectedStationButton.ModulateSelfOverride = Color.FromHex("#274c8d");

            _selectedStation = stationId;
            OnStationSelected?.Invoke(stationId);
        }
    }
}