// SPDX-FileCopyrightText: 2021 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2021 moonheart08 <moonheart08@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 Rinkashikachi <15rinkashikachi15@gmail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Morb <14136326+Morb0@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using Content.Shared._CorvaxGoob.CCCVars;
using Content.Shared._CorvaxGoob.TTS;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections.Generic;
using System.Linq;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminAnnounceWindow : DefaultWindow
    {
        [Dependency] private readonly ILocalizationManager _localization = default!;
        [Dependency] private readonly IConfigurationManager _cfgManager = default!; // CorvaxGoob-TTS
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!; // CorvaxGoob-TTS

        private List<TTSVoicePrototype> _voiceList = new(); // CorvaxGoob-TTS

        public AdminAnnounceWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Announcement.Placeholder = new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));
            // Vortex-PlayableCentCom-Edit-Start
            Announcer.Text = _localization.GetString("admin-announce-announcer-default");
            SoundInput.Text = "/Audio/_CorvaxGoob/Announcements/centcomm.ogg"; // Default to announce sound
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-all-stations"));
            AnnounceMethod.SetItemMetadata(0, AdminAnnounceType.AllStations);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-specific-station"));
            AnnounceMethod.SetItemMetadata(1, AdminAnnounceType.SpecificStation);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-server"));
            AnnounceMethod.SetItemMetadata(2, AdminAnnounceType.Server);
            AnnounceMethod.OnItemSelected += AnnounceMethodOnOnItemSelected;

            StationSelector.OnItemSelected += args => StationSelector.SelectId(args.Id);
            Announcement.OnKeyBindUp += AnnouncementOnOnTextChanged;
            // Vortex-PlayableCentCom-Edit-End

            // CorvaxGoob-TTS-Start
            if (_cfgManager.GetCVar(CCCVars.TTSEnabled))
            {
                TTSContainer.Visible = true;
                InitializeVoice();
            }
            // CorvaxGoob-TTS-End
        }

        // CorvaxGoob-TTS-Start
        private void InitializeVoice()
        {
            _voiceList = _prototypeManager
                .EnumeratePrototypes<TTSVoicePrototype>()
                .OrderBy(o => Loc.GetString(o.Name))
            .ToList();

            VoiceButton.AddItem(Loc.GetString("tts-voice-none"));
            VoiceButton.SetItemMetadata(0, "None");

            for (var i = 1; i < _voiceList.Count; i++)
            {
                var name = Loc.GetString(_voiceList[i].Name);
                VoiceButton.AddItem(name);
                VoiceButton.SetItemMetadata(i, _voiceList[i].ID);
            }

            VoiceButton.OnItemSelected += args =>
            {
                VoiceButton.SelectId(args.Id);
            };
        }
        // CorvaxGoob-TTS-End

        private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
        {
            AnnounceButton.Disabled = Rope.Collapse(Announcement.TextRope).TrimStart() == "";
        }

        private void AnnounceMethodOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            AnnounceMethod.SelectId(args.Id);
            // Vortex-PlayableCentCom-Edit-Start
            var type = (AdminAnnounceType?)args.Button.SelectedMetadata ?? AdminAnnounceType.AllStations;
            Announcer.Editable = type == AdminAnnounceType.AllStations || type == AdminAnnounceType.SpecificStation;
            StationSelector.Visible = type == AdminAnnounceType.SpecificStation;
            TTSContainer.Visible = _cfgManager.GetCVar(CCCVars.TTSEnabled) && (type == AdminAnnounceType.AllStations || type == AdminAnnounceType.SpecificStation); // CorvaxGoob-TTS
        }

        public void SetStations(Dictionary<NetEntity, string> stations)
        {
            StationSelector.Clear();
            foreach (var (netEntity, name) in stations)
            {
                StationSelector.AddItem(name);
                StationSelector.SetItemMetadata(StationSelector.ItemCount - 1, netEntity);
            }
            // No default selection
        }
        // Vortex-PlayableCentCom-Edit-End

        private void OnSoundInputTextChanged(LineEdit.LineEditEventArgs args)
        {
            SoundInput.ModulateSelfOverride = null;
        }
    }
}
