using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Vortex.Description;

[GenerateTypedNameReferences]
public sealed partial class DescriptionTab : Control
{
    public Action<string>? OnFlavorTextChanged;
    public Action<string>? OnOOCNotesChanged;

    public DescriptionTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var loc = IoCManager.Resolve<ILocalizationManager>();
        CFlavorTextInput.Placeholder = new Rope.Leaf(loc.GetString("flavor-text-placeholder"));
        CFlavorTextInput.OnTextChanged += _ => FlavorTextChanged();

        COOCNotesInput.Placeholder = new Rope.Leaf(loc.GetString("ooc-notes-placeholder"));
        COOCNotesInput.OnTextChanged += _ => OOCNotesChanged();
    }

    private void FlavorTextChanged()
    {
        OnFlavorTextChanged?.Invoke(Rope.Collapse(CFlavorTextInput.TextRope).Trim());
    }

    private void OOCNotesChanged()
    {
        OnOOCNotesChanged?.Invoke(Rope.Collapse(COOCNotesInput.TextRope).Trim());
    }

    public void SetFlavorTextVisible(bool visible)
    {

    }

    public void SetOOCNotesVisible(bool visible)
    {

    }

    public void UpdateFlavorText(string text)
    {
        CFlavorTextInput.TextRope = new Rope.Leaf(text);
    }

    public void UpdateOOCNotes(string text)
    {
        COOCNotesInput.TextRope = new Rope.Leaf(text);
    }
}