// SPDX-FileCopyrightText: 2022 Julian Giebel <juliangiebel@live.de>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.UserInterface.CustomControls;
using System.Text;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NotekeeperUiFragment : BoxContainer
{
    public event Action<int>? OnNoteSelected;
    public event Action? OnBackButtonPressed;
    public event Action? OnCreateNewNote;
    public event Action<int, string, string>? OnSaveNote;
    public event Action<int>? OnDeleteNote;
    public event Action<int>? OnViewNote;

    private int? _currentEditingNoteId = null;
    private int? _currentViewingNoteId = null;
    private const int MaxLineLength = 55;

    public NotekeeperUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        BackButton.OnPressed += _ => OnBackButtonPressed?.Invoke();
        SaveButton.OnPressed += _ => SaveCurrentNote();
        DeleteButton.OnPressed += _ => { if (_currentEditingNoteId.HasValue) OnDeleteNote?.Invoke(_currentEditingNoteId.Value); };
        EditButton.OnPressed += _ =>
        {
            if (_currentViewingNoteId.HasValue)
                OnNoteSelected?.Invoke(_currentViewingNoteId.Value);
        };
        NewNoteButton.OnPressed += _ => OnCreateNewNote?.Invoke();
    }

    private string AddWordWrapping(string text)
    {
        if (string.IsNullOrEmpty(text))
            return text;

        var words = text.Split(' ');
        var result = new StringBuilder();
        var currentLineLength = 0;

        foreach (var word in words)
        {
            // Если слово само по себе длиннее максимальной длины строки
            if (word.Length > MaxLineLength)
            {
                // Если текущая строка не пустая, добавляем перенос
                if (currentLineLength > 0)
                {
                    result.AppendLine();
                    currentLineLength = 0;
                }

                // Разбиваем длинное слово
                for (int i = 0; i < word.Length; i += MaxLineLength)
                {
                    var chunk = word.Substring(i, Math.Min(MaxLineLength, word.Length - i));
                    if (i > 0)
                        result.AppendLine();
                    result.Append(chunk);
                }
                currentLineLength = word.Length % MaxLineLength;
                if (currentLineLength == 0)
                    currentLineLength = MaxLineLength;
            }
            else
            {
                // Проверяем, поместится ли слово на текущей строке
                if (currentLineLength + word.Length + (currentLineLength > 0 ? 1 : 0) > MaxLineLength)
                {
                    result.AppendLine();
                    currentLineLength = 0;
                }

                // Добавляем пробел перед словом, если это не первое слово в строке
                if (currentLineLength > 0)
                {
                    result.Append(' ');
                    currentLineLength++;
                }

                result.Append(word);
                currentLineLength += word.Length;
            }
        }

        return result.ToString();
    }

    public void UpdateListState(List<NoteData> notes)
    {
        NotesListView.Visible = true;
        NoteEditorView.Visible = false;
        NoteViewView.Visible = false;
        BackButton.Disabled = true;

        NotesListContainer.RemoveAllChildren();

        // Add existing notes
        foreach (var note in notes)
        {
            var noteButton = new Button
            {
                Text = string.IsNullOrEmpty(note.Title) ? Loc.GetString("notekeeper-ui-untitled-note") : note.Title,
                HorizontalExpand = true,
                Margin = new Thickness(2, 2, 2, 2)
            };
            noteButton.OnPressed += _ => OnViewNote?.Invoke(note.Id);
            NotesListContainer.AddChild(noteButton);
        }
    }

    public void UpdateViewState(NoteData note)
    {
        NotesListView.Visible = false;
        NoteEditorView.Visible = false;
        NoteViewView.Visible = true;
        BackButton.Disabled = false;

        _currentViewingNoteId = note.Id;
        NoteViewTitleLabel.Text = note.Title;

        // Добавляем перенос текста для содержимого заметки
        var wrappedContent = AddWordWrapping(note.Content);
        NoteViewContentLabel.SetMessage(FormattedMessage.FromMarkupPermissive(wrappedContent));
    }

    public void UpdateEditorState(NoteData note)
    {
        NotesListView.Visible = false;
        NoteEditorView.Visible = true;
        NoteViewView.Visible = false;
        BackButton.Disabled = false;

        _currentEditingNoteId = note.Id;
        TitleInput.Text = note.Title;
        ContentInput.TextRope = new Rope.Leaf(note.Content);
    }

    private void SaveCurrentNote()
    {
        if (_currentEditingNoteId.HasValue)
        {
            var title = TitleInput.Text.Trim();
            var content = Rope.Collapse(ContentInput.TextRope);
            OnSaveNote?.Invoke(_currentEditingNoteId.Value, title, content);
        }
    }
}