using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.OOCNotes;

[GenerateTypedNameReferences]
public sealed partial class OOCNotes : Control
{
    public Action<string>? OnOOCNotesChanged;

    public OOCNotes()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var loc = IoCManager.Resolve<ILocalizationManager>();
        COOCNotesInput.Placeholder = new Rope.Leaf(loc.GetString("ooc-notes-placeholder"));
        COOCNotesInput.OnTextChanged += _ => OOCNotesChanged();
    }

    public TextEdit OOCNotesInput => COOCNotesInput;

    public void OOCNotesChanged()
    {
        OnOOCNotesChanged?.Invoke(Rope.Collapse(COOCNotesInput.TextRope).Trim());
    }
}